language: python
python:
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "nightly" # currently points to 3.7-dev

install: "pip install poetry"

script:
  - poetry install
  - poetry run pytest
